name: build-deploy-parcel
run-name: Build and Deploy with Parcel
on:
  push:
    branches:
      new


jobs:
  build_app:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Install dependencies
          run: |
           npm i
        
        - name: Build site
          run: |
           npm run build
        
        - name: Deploy site to gh-pages branch
          run: |
           npm run deploy