name: build-deploy-parcel
run-name: Build and Deploy with Parcel
on:
  push:
    branches:
      new


jobs:
  build_app:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Install dependencies
          run: |
           npm i
        
        - name: Build site
          run: |
           npm run build
        
        - name: Deploy site using gh-pages
          run: |
           git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
           npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
